* OS
[[./part-resize.org][关于分区大小调整和备份]]
** linux tool list
guake terminal, byubo, tmux
nautilus actions
top shelf
cairo
** archlinux							       :arch:
*** skype sound
cat .pulse/client.conf
autospawn=no
pkill pulseaudio
skype 配置声音(这时用的alsa)

Restore ALSA Mixer settings at startup
alsactl -f /var/lib/alsa/asound.state store
add alsa to rc.conf or add following to rc.local
alsactl -f /var/lib/alsa/asound.state restore

*** wget下载pacman
XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
*** chsdir的安装
yaourt 过期.
下载最新源包, pacman 安装 bash-completion, chsdir 首行的 python 改成 python2

*** fbterm 的中文输入
ibus-fbterm 总是无法正常使用.
yaourt 安装 yong (小小输入法), 修改配置文件, 仅使用拼音和五笔. 
Ctrl + Space 关闭输入法再打开, 如果不能输入, 可 Ctrl + Shift 切换出来输入法.

----
总结: 多阅读 man 和自带 doc 文档, 阅读软件主页说明.
*** install fvwm
安装了fvwm, awesome (yaourt). 但无法起动awesome, 因为没有安装xorg. 安装xorg-server, xorg-xinit, xorg-utils, xf86-video-intel, 可以起动了.

*** 软件依赖冲突
ssh 翻墙，安装openssh时2个软件包有冲突，需要用pacman -Syu解决. 

*** 自定义rox的快捷键
修改~/.gtkrc-2.0
gtk_can_change_accels=1

a*** aliedit
支付宝安全控件直接安装不起作用，网上查得信息并成功安装：
1. .aliedit/下log文件可知安装过程，是在.mozilla/plugins下copy一个库文件。
2. ldd 该库文件知链接中的库文件libpng12没有。
3. arch版本更新快，libpng已是14。
4. 用yaourt安装aliedit，可自动进行libpng12的下载、编译安装。
*** 安装
使用 UNetbootin 将 iso 写入优盘，优盘启动引导，提示找不到盘符。

这是因为 arch 安装程序按照 LABEL 找 iso 文件。这时需先修改启动参数，增加
	: archisolabel=ARCH_201005

再如下手动加载iso：
#+BEGIN_SRC shell-script
mkdir /iso
mount -t ext3 /dev/sda7 /iso
modprobe loop
losetup /dev/loop6
ln -s /dev/loop6 /dev/disk/by-label/ARCH_201005
#+END_SRC

Ctrl-D退出后，即可进入安装界面。

*** 配置

添加用户
	: useradd -m -g users -G audio,lp,optical,storage,video,wheel,games,power -s /bin/bash archie

eth0="dhcp"
wlan0="dhcp"
wlan_wlan0="wlan0 essid MyEssid" # Unencrypted
#wlan_wlan0="wlan0 essid MyEssid key 1234567890" # hex WEP key
#wlan_wlan0="wlan0 essid MyEssid key s:asciikey" # ascii WEP key
INTERFACES=(eth0 wlan0)

xorgcfg 
xorgconfig
*** DONE 输入时禁用 touchpad					   :touchpad:
   - State "DONE"       [2010-09-14 二 17:19]

     使用以下命令，效果强过图形界面设置。
    :PROPERTIES:
     :ARCHIVE_TIME: 2010-12-11 六 20:06
    :END:
#+BEGIN_SRC shell-script
   syndaemon -d -i 3 -t
#+END_SRC

 | -d   | daemon 模式                     |
 | -t   | 仅禁用点击、滚动，可以移动鼠标  |
 | -i 3 | 键盘释放3秒后恢复 touchpad 功能 |
*** DONE texlive use						      :LINUX:
    :PROPERTIES:
    :ARCHIVE_TIME: 2011-08-05 五 08:12
    :END:
pacman 安装了 arch 系统的一些 texlive 软件包，发现宏包不全，且没有 tlmgr 的在线安装宏包功能。
缷载软件包后，又用texlive的网络安装功能重新安装系统，适当多选了些软件组。

重新编译我的答辩幻灯，xeCJK的参数设置又有变化，缺slashbox宏包，且CTAN上也没有。
单独下载了slashbox宏包，放在/usr/local/texlive/texmf-local/tex/latex/local/下面，再texhash即可。
*** DONE init5; firefox->2;					      :LINUX:
    :PROPERTIES:
    :ARCHIVE_TIME: 2011-08-05 五 08:12
    :END:
  - 命令行方式的自动登录到fvwm，参见https://wiki.archlinux.org/index.php/Start_X_at_Boot
    1) 小c程序：autologin
    2) .bash_profile: startx
  - Style StartsOnDesk 0 

** gentoo安装							     :gentoo:

X -retro -config /root/xorg.conf.new
** DONE [#C] fvwm 托盘区					:@HOME:LINUX:
   CLOSED: [2011-08-17 三 22:37]
   - State "DONE"       from "TODO"       [2011-08-17 三 22:37]
        $ sudo apt-get install trayer
        $ trayer --widthtype pixel --width 128 --height 32 --edge bottom &
    :PROPERTIES:
    :ARCHIVE_TIME: 2011-08-17 三 22:38
    :END:

已经困扰我好几天的问题了，想在fvwm里面使用托盘，但是老是不成功，试了好几个tray程
序，如trayer等，都不能完美的swallow。但是单独使用是没有问题的。但我希望能swallow
到fvwmbuttons里面（因为我用的fvwmbuttons做的taskbar)。今天再次仔细的阅读了
stalonetray的man页。然后终于成功了，HOHO，非常的完美，只需要一个参数p参数就OK。表
示使用父颜色。如下： *FvwmTopBar: (100×25+885+0,Swallow(NoClose, UseOld)
`stalonetray` `Exec exec stalonetray -p`)
** DONE fvwm-crystal
   CLOSED: [2011-08-28 日 20:00]
   - State "DONE"       from "TODO"       [2011-08-28 日 20:00]
 - keyboard-modifier
 - fvwm-crystal.apps
python2; with-->without; recipes: with-->without
 - Script-Clock: default to 24-mode
 - userconfig
 - bindings: Pager
 - recipe: 
   1) EdgeRistance
   2) app-menu static
   3) $[fvwm_font]
   4) remove numpad bindings
   5) Pager

** win
*** 休眠和唤醒
**** 休眠
 1. 控制面板-电源-休眠功能-开启
 2. 关机界面按 Shift, 待机变成休眠
 3. 自动休眠命令
#+BEGIN_EXAMPLE
at 11:30 rundll32.exe powrprof.dll,SetSuspendState
#+END_EXAMPLE
**** 唤醒
bios-apm-power RTC alarm from S5 *enable*
*** at命令
  1. 时间格式只有时分，时期和星期需要用 =/next:= 和 =/every:= 来指定。
  2. 命令行命令如 =del= 等前面需要加 =cmd /c= ，否则无法执行。
*** avira广告去除
组策略-windows设置-安全设置-软件限制策略-其它规则-新建

=c:\Program Files\Avira\AntiVir Desktop\avnotify.exe=

<=c:\Program Files\Avira\AntiVir Desktop\avnotify.dll=

*** win7自动登录
=control userpasswords2=
=netplwiz=
* Office
** word
*** 叠字效果
在表格中，需要选中方框时。
 1. 重叠的两个无边框文本框，每个里面1个字
 2. 前1个字的字符间距，紧缩12磅（5号字）
 3. {eq \o (a,b)}
*** TOC域目录生成
**** 证明材料目录的自动生成
#+begin_verse
{TC 目录中文字 \f a \l 1}
{TOC \f a \h}
#+end_verse
前者做a类型隐藏标记, 后者根据其生成目录. \l表示目录文字采用"目录1"样式, \h表示加超链接.

可以先按顺序做好文字序列, 再Alt+Shift+o生成TC域, 插入图, 自动生成目录.

**** 域开关
TOC域通过下面的开关创建目录:
#+begin_verse
\f 目录项
\o 标题级别
\u 大纲级别
\a 题注
\b 书签
\c seq域 \s页前加章节号,\d章节号和页号分隔符
\t 样式
#+end_verse

其它的开关选项有:
#+begin_verse
\p 目录名和页码之间分隔符
\w 保留制表符项
\x 保留换行符
#+end_verse

*** seq域和listnum域
域字体格式可和正文一样用样式确定. 
数字的样式listnum域比seq域复杂, 默认三种表里, 各9个级别. 还可以用多级符号制作自己的表.

#+begin_verse
listnum \l level \s startNum
#+end_verse

*** 方框选中符号
格式－中文－带圈符号
*** 制表符使用2则
  1. 目录使用的是右对齐，前导...的制表符
  2. 落款使用的是合适位置居中对齐的制表符
*** 网络打印机安装
 1. 连接－属性－TCP/IP－属性－高级－WINS－启用NetBios
 2. 连接－属性－安装－服务－Microsoft网络的文件和打印机共享
 3. 连接－属性－高级－防火墙－例外，中有文件和打印机共享
 4. 服务－Computer Browser 启动
-----
 1. 启动Guest来宾帐户
 2. 计算机管理－系统工具－本地用户和组－用户－Guest账户：全取消
-----
 1. gpedit.msc－本地计算机策略－计算机配置－Windows配置－安全设置－本地策略－用户权利指派，拒绝从网络访问；从网络访问
 2. 接上，本地安全策略－用户权限指派，空密码用户
-----
 1. 计算机属性－网络ID，改成不使用域，工作组GROUP309
 2. regedit, HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa 上将此子健中的值 restrictanonymous设为0就行了

补充说明
 + host文件，fsmgmt.msc可以查看目前共享
 + 本地安全策略中：经典登录
 + 文件夹选项－简单文件共享
 + 文件夹权限

*** DONE [#C] word博士模板
   CLOSED: [2011-08-14 日 16:01]
   - State "DONE"       from "HANGUP"     [2011-08-14 日 16:01]
 - word 常用域
{FORMTEXT}
{TOC \t "NUDT标题1,1,NUDT标题2,2,NUDT标题3,3" \h}
{TOC \t "NUDT表" \c \h}

*** DONE [#C] ps 大字打印
   - State "DONE"       [2011-03-06 日 09:38]
    :PROPERTIES:
    :ARCHIVE_TIME: 2011-07-24 日 17:37
    :END:
word excel 联手打大字。比如在Word A4页面中打一个汉字，
放大到这一个字满幅（可先选中这个字，Ctrl+］），复制，
到Excel中选择性粘贴为图片，拖大到四张A4幅面大小即可打印了。
（可以将Excel预览一下，视图调成25%左右大小）

第1步，打开Word2003窗口，输入一个汉字，并设置字号使其满屏（在Word中一般设置为500号字比较合适）页面中输入一个汉字。
第2步，选中该大字并执行“复制”操作，然后打开Excel窗口，在菜单栏依次单击“编辑”→“选择性粘贴”菜单命令，打开“选择性粘贴”对话框。在“方式”列表框中选中“图片（增强型图元文件）”选项，并单击“确定”按钮，如图2008071001所示。
第3步，在Excel窗口中设置执行为A4，并设置显示比例为25%。然后拖动大字图片周围的控制块调整其大小，使其符合几张A4纸型的幅面即可打印，如图2008071002所示。

借助于专门的海报打印软件来解决

office2003也有类似的功能~有专门的超大字打印程序
** TeX
*** bst file                                                                    :bst:

    bst文件中STRINGS变量不能超过20.
